version: '2'
services:
  ember:
    image: kbluescode/ember:l-and-l
    volumes:
      - $GOHOME/lunch-and-learn/frontend:/app
    ports:
      - "4200:4200"
      - "45912:45912"
  postgres:
    image: kbluescode/postgres 
  api:
    image: kbluescode/go-api
    ports:
      - "3000:3000"
